# Node.js
- task: Npm@1
  inputs:
    command: 'install'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '検証用サブスクリプション(736a95bb-7bc5-4237-a510-96c1c4f7bf2d)'
    appType: 'webApp'
    WebAppName: 'demoyabe-webapp-pipeline-node'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
